spring:
  application:
    name: BookService
  h2:
     console:
       enabled: true
       path: /h2
  datasource:
      url: jdbc:h2:mem:books
      username: root
      password: root
      driverClassName: org.h2.Driver


server:
  port: 8100

