spring:
  application:
    name: OrderService
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:order
    username: root
    password: root
    driverClassName: org.h2.Driver


server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
